project:add.o sort.o show.o refresh.o manu.o del.o mod.o del_all.o save.o reverse.o
	cc -g -o project add.o sort.o refresh.o show.o manu.o del.o mod.o del_all.o reverse.o save.o
add.o:add.c
	cc -g -c add.c -o add.o	
refresh.o:refresh.c
	cc -g -c refresh.c -o refresh.o
sort.o:sort.c
	cc -g -c sort.c -o sort.o
show.o:show.c
	cc -g -c show.c -o show.o
manu.o:manu.c
	cc -g -c manu.c -o manu.o
del.o:del.c
	cc -g -c del.c -o del.o	
mod.o:mod.c
	cc -g -c mod.c -o mod.o
del_all.o:del_all.c
	cc -g -c del_all.c -o del_all.o
save.o:save.c
	cc -g -c save.c -o save.o
reverse.o:reverse.c
	cc -g -c reverse.c -o reverse.o

